#!/bin/bash
# Pre-commit hook: Enforce feature branch workflow
# Generated by pre-commit-enforce skill
# Do not edit directly — modify skill config or reinstall skill

set -e

# Source helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT=$(git rev-parse --show-toplevel)
SKILL_ROOT="$REPO_ROOT/.claude/skills/pre-commit-enforce"

source "$SKILL_ROOT/src/helpers.sh"

# Get current branch
BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Get protected branches from config
PROTECTED=$(get_protected_branches)

# Check if current branch is protected
is_protected() {
  local branch="$1"
  local protected_list="$PROTECTED"

  for protected in $protected_list; do
    if [ "$branch" = "$protected" ]; then
      return 0
    fi
  done
  return 1
}

# Main enforcement
if is_protected "$BRANCH"; then
  log_error "$(get_message)"
  echo ""
  echo "Current branch: $BRANCH"
  echo ""
  echo "Proper workflow:"
  echo "  1. Create feature branch: git checkout -b feat/issue-XXX-description"
  echo "  2. Commit changes: git commit -m '...'"
  echo "  3. Push branch: git push -u origin feat/issue-XXX-description"
  echo "  4. Create PR on GitHub"
  echo "  5. Merge via PR"
  echo ""
  exit 1
fi

exit 0
